# Generated by Django 4.2 on 2023-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interesado",
            name="cuit",
            field=models.CharField(default="cuit", max_length=40),
        ),
        migrations.AddField(
            model_name="interesado",
            name="organizacion",
            field=models.CharField(default="org", max_length=40),
        ),
        migrations.AlterField(
            model_name="interesado",
            name="apellido",
            field=models.CharField(default="apellido", max_length=20),
        ),
        migrations.AlterField(
            model_name="interesado",
            name="email",
            field=models.EmailField(default="mail", max_length=40),
        ),
        migrations.AlterField(
            model_name="interesado",
            name="nombre",
            field=models.CharField(default="nombre", max_length=40),
        ),
    ]
