# Generated by Django 4.2 on 2023-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0003_consultoria"),
    ]

    operations = [
        migrations.DeleteModel(name="Consultoria",),
        migrations.AddField(
            model_name="interesado",
            name="servicio",
            field=models.CharField(default="serv", max_length=40),
        ),
    ]
