# Generated by Django 4.2 on 2023-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0004_delete_consultoria_interesado_servicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interesado",
            name="servicio",
            field=models.CharField(default="consultorias varias", max_length=40),
        ),
    ]
