# Generated by Django 4.2 on 2023-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0005_alter_interesado_servicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteresadoTalleres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taller", models.CharField(default="varios", max_length=40)),
                ("comision", models.CharField(default="4123", max_length=40)),
            ],
        ),
    ]
