# Generated by Django 4.2 on 2023-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0006_interesadotalleres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taller", models.CharField(default="Otros", max_length=40)),
                ("comision", models.CharField(default="1234", max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name="interesadotalleres",
            name="nombre",
            field=models.CharField(default="faltante", max_length=40),
        ),
    ]
