# Generated by Django 4.2 on 2023-10-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0007_taller_interesadotalleres_nombre"),
    ]

    operations = [
        migrations.RemoveField(model_name="interesadotalleres", name="comision",),
    ]
