# Generated by Django 4.2 on 2023-11-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0008_remove_interesadotalleres_comision"),
    ]

    operations = [
        migrations.CreateModel(
            name="TallerBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="TallerInscriptos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="faltante", max_length=40)),
                ("taller", models.CharField(default="varios", max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="interesadotalleres",
            name="nombre",
            field=models.CharField(default="Tu nombre", max_length=40),
        ),
        migrations.CreateModel(
            name="IncripcionTaller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBlog.tallerbase",
                    ),
                ),
            ],
        ),
    ]
